<?php

/*     MOD CONFIGURATION    */
const LOOT_MULTIPLIER = "5";
const POTION_STACKABLE_LIMIT = 100;
const RARE_LOOT_VENDOR_COST_MULTIPLE = 5;
//const CONJURED_ITEM_BUFFRATE = 0.5;
const CAST_TIME_FOR_MISC = 0;
//const UNCOMMON_LOOT_VENDOR_COST_MULTIPLE = 1;